#!/usr/bin/env bash

rm -rf release test
mkdir release test

VERSION=`grep AC_INIT ../configure.ac | awk -e '{print $2}' | tr -d ')[],'`
#echo "VERSION=*${VERSION}*"
TARBALL="neoleo-$VERSION.tar.gz"
MD5SUM=`md5sum ../$TARBALL | cut -d " " -f 1 | tr -d "\n"`
#echo "MD5SUM=$MD5SUM"

function run_m4() {
	m4 -D VERSION=$VERSION -D MD5SUM=$MD5SUM -D SOURCE="$SOURCE"   PKGBUILD.m4 > $2/PKGBUILD 
}



SOURCE="file://$TARBALL"
#echo $SOURCE

#m4 -D VERSION=$VERSION -D MD5SUM=$MD5SUM -D SOURCE="$SOURCE"   PKGBUILD.m4 > test/PKGBUILD
run_m4 $SOURCE test
cp ../$TARBALL test

SOURCE='https://github.com/blippy/neoleo/releases/download/v$pkgver/$pkgname-$pkgver.tar.gz'
run_m4 $SOURCE release
