#!/usr/bin/env bash

# mcarter 22-Dec-2016 my own configuration experiments.
# Everyone else should ignore this file

if [ ! -f configure ]; then
	autoreconf -iv
fi


source /etc/os-release
if [ "x$OS" = "xWindows_NT" ]; then ID=Windows_NT ; fi
case "$ID" in
	ubuntu) OPTS="--with-debug --with-coverage --with-asan" ;;
	#ubuntu) OPTS="--with-debug" ;;
	#ubuntu) OPTS="--with-debug --with-coverage" ;;
	slackware) OPTS="--with-debug" ;;
	*) ;;
esac

#if [[ ":Windows_NT:raspbian:slackware:" = *:$ID:* ]]; then	
#	SAN=
#	COV=
#fi

#GPPOF=--with-prof
#OPTS="$DBG $GPROF $SAN $COV "

#./configure $GPROF $SAN "CXXFLAGS=  -O0 -g" --prefix=$HOME/.local
./configure $OPTS  --prefix=$HOME/.local

