#!/usr/bin/env bash

# mcarter 22-Dec-2016 my own configuration experiments.
# Everyone else should ignore this file

#./configure 'CFLAGS=-O0 -g' --prefix=$HOME/.local


#MX=--with-motif # default: commented
#SAN=-fsanitize=address
#SAN=--with-asan

#./configure $MX $SAN "CFLAGS= -Werror  -O0 -g " "CXXFLAGS=  -O0 -g" --prefix=$HOME/.local
./configure $MX $SAN "CXXFLAGS=  -O0 -g" --prefix=$HOME/.local



