@node Examples and Utilities, Macros, Printing and Plotting, Top
@chapter Examples and Utilites
@cindex Examples
@cindex Utilities

Examples and utilities are installed into the directory
@code{share/neoleo/examples}, somewhere on the hard drive. To determine
the exact location, type `@code{neoleo --version}', and look at
the line beginning `@code{Datadir:}'.

@section oleo.pm6
@cindex oleo.pm6

@code{oleo.pm6} is a perl6 script that converts @code{neoleo} format 
from stdin to CSV on stdout. For example:
@example
./neoleo.pm6 <foo.oleo >foo.csv
@end example

BUG: omits cells that have formulae in them.

