@node Forth Interpreter, Extending Oleo, Functions, Top
@chapter Forth Interpreter
@cindex Forth

@menu
* Forth::		Implementation-specific notes on atlast
* Calling Forth::	How to invoke Forth from oleo
* Oleo words::		Forth words specific to oleo
@end menu

@node Forth, Calling Forth, Forth Interpreter, Forth Interpreter
@section Implementation-specific notes on atlast
@code{Oleo} embeds John Walker's Public domain @code{atlast}
64-bit interpreter. It uses version 2.0. Further details can be found 
@url{https://www.fourmilab.ch/atlast/, here}.
A general programming guide and words are available
@url{file://atlast2.html, here},
and is quite extensive.

Technical details for developers are outlined in Technical Release TR04,
which is within the TR directory of the source distribution.

@b{Strings} should be enclosed in double-quotes, like so:
@example
"hello world"
@end example
Unlike most Forths, `"' is not a separate word, so there is no need
to put whitespace after it at the start of the string. This 
principle also works in definitions:
@example
: hi "hello world" type cr ;
@end example
Double-quotes are placed in strings by escaping them with `\':
@example
"\"Quoth the raven\""
@end example

The rest of this document only concentrates on @code{Oleo}-specific 
Forth concepts.
Only a proof-of-concept word (@code{4life}) has been added at this
stage, but it is hoped that more words will be added in due course.
The infrastructure is already there.

@node Calling Forth, Oleo words, Forth, Forth Interpreter
@section How to invoke Forth from oleo

@table @code
@item M-x forth
@cmindex forth
This command evaluates the input you supply using the Forth interpreter. For
example, set the current cell to the value `42':
@example
M-x forth <RET> 4life <RET>
@end example

A fancier example:
@example
M-x forth <RET> 2 3 + . cr <RET>
@end example
Adds 2 and 3 together to give 5. `.' prints the top of the stack: in this
case it will be 5. `cr' prints a newline. NB: 1) use `cr' to ensure the 
output is flushed to the terminal, 2) you will probably only want to 
execute the command when @code{neoleo} is using an X-windows display,
as the output will interfere with ncurses displays.

@end table

@node Oleo words, Extending Oleo, Calling Forth, Forth Interpreter
@section Forth words specific to oleo 
A list of @code{Oleo}-specific words now follows.

@table @code
@item 4life
Sets the current cell to `42'. Currently only useful only as a 
proof-of-concept, of course.
@end table

