.TH NEOLEO 1
.SH NAME
neoleo \- ncurses spreadsheet
.SH SYNOPSIS
.B neoleo
[\fIOPTION\fR]
[\fIFILE\fR]
.SH DESCRIPTION
.B neoleo
is a lightweight spreadsheet based on the venerable GNU Oleo project. Keybindings are styled after vim.

Type:
.nf
info neoleo
.fi
for complete documentation, or 
.nf
neoleo -h 
.fi
for an overview of command-line options
