/* Automatically generated by po2tbl.sed from oleo.pot.  */

#if HAVE_CONFIG_H
# include <config.h>
#endif

#include "libgettext.h"

const struct _msg_ent _msg_tbl[] = {
  {"", 1},
  {"\
This is %s %s\n\
\n", 2},
  {"Usage: %s [OPTION]... [FILE]...\n", 3},
  {"\
\n\
  -h, --help               display this help and exit\n\
  -V, --version            output version information and exit\n\
  -q, --quiet              do not display startup messages\n\
  -f, --ignore-init-file   ignore settings defined in init file\n\
  -t, --no-toolkit         disable X toolkit\n\
  -x, --nw                 disable graphics and fallback to curses\n\
  -s x, --separator x\t   set separator for 'list' file type to x\n\
  -S, --space\t\t   set separator for 'list' file type to a space\n\
  -F x, --format x\t   set default file type to x (oleo, list, sc  ...)\n\
  --filter\t\t   read file from stdin, write to stdout on exit\n\
\n\
Report bugs to <bug-oleo@gnu.org>.\n", 4},
  {"%s %s\n", 5},
  {"Copyright © 1992-2000 Free Software Foundation, Inc.\n", 6},
  {"%s comes with ABSOLUTELY NO WARRANTY.\n", 7},
  {"You may redistribute copies of %s\n", 8},
  {"under the terms of the GNU General Public License.\n", 9},
  {"For more information about these matters, ", 10},
  {"see the files named COPYING.\n", 11},
  {"Error in the builtin init scripts (a bug!).\n", 12},
  {"   error occured in init file %s near line %d.", 13},
  {", error occured reading '%s'\n", 14},
  {"Can't open %s: %s\n", 15},
  {"Fit Print Area", 16},
  {"Conversion error: cannot convert '%s' to a %s\n", 17},
  {"Cannot find XmNuserData\n", 18},
  {"range", 19},
  {"Plotter Type", 20},
  {"*.oleo", 21},
  {"X Axis Tick Label Type", 22},
  {"Y Axis Tick Label Type", 23},
  {"Internal error: can't find what to print to\n", 24},
  {"*.out", 25},
  {"\
Value of defaultPrintTo resource is invalid, should be one of %s, %s, or %s\n", 26},
  {"Select Printer", 27},
  {"Paper Format", 28},
  {"Printer Language", 29},
  {"File Format", 30},
  {"[Oleo: %s]", 31},
  {"Read file '%s'\n", 32},
  {"Choose a file to load", 33},
  {"\
There are unsaved changes.\n\
Do you want to quit anyway ?", 34},
  {"OleoOpenForWrite: can't move %s to %s", 35},
  {"OleoOpenForWrite: couldn't open file '%s' for write", 36},
  {"ReallySaveCB(%s): couldn't open file for writing", 37},
  {"ReallySaveCB: file close failed", 38},
  {"Saved file '%s'\n", 39},
  {"ReallySaveCB: couldn't figure out file to save into", 40},
  {"Choose a file to save in", 41},
  {"\
<html><body>Can't find the requested help file\n\
</body></html>", 42},
  {"Help requested on '%s'", 43},
  {"Help requested on using Oleo", 44},
  {"OK", 45},
  {"Cancel", 46},
  {"Copy a region", 47},
  {"Copy Values", 48},
  {"Move", 49},
  {"Formats :", 50},
  {"Default", 51},
  {"Hidden", 52},
  {"Graph", 53},
  {"General", 54},
  {"Dollar", 55},
  {"Comma", 56},
  {"Percent", 57},
  {"Integer", 58},
  {"Decimal", 59},
  {"Fixed", 60},
  {"Exponent", 61},
  {"Date", 62},
  {"User-1", 63},
  {"User-2", 64},
  {"User-3", 65},
  {"User-4", 66},
  {"Date Format", 67},
  {"XmProcessTraversal failed\n", 68},
};

int _msg_tbl_length = 68;
