.TH NEOLEO 1
.SH NAME
neoleo \- ncurses spreadsheet
.SH SYNOPSIS
.B neoleo
[\fIOPTION\fR]
[\fIFILE\fR]
.SH DESCRIPTION
.B neoleo
is a lightweight spreadsheet based on the venerable GNU Oleo project. Keybindings are styled after vim.
.SH OPTIONS
.TP
.BR \-H ", " \-\-headless
Run in headless mode (without ncurses front-end)
.TP
.BR \-h ", " \-\-help
Show command\-line options
.TP
.BR \-T ", " \-\-tests =\fBX\fR
Run test suite X.
.TP
.BR \-V ", " \-\-version
Show version



.SH KEY BINDINGS
Main window commands:

.ie c \[shc] \
.  ds softhyphen \[shc]
.el \
.  ds softhyphen \(hy
.na
.TS
tab (@);
l l.
Key@Meaning
_
\[eq]@Edit a cell
r@Perform row command
C-c@copy cell formula to clipboard
C-l@set cell alignment left
C-q@quit
C-r@set cell alignment right
C-s@save document
C-t@save document as CSV file
C-v@paste cell formula from clipboard
.TE
.ad

Up, down, left, right and delete keys should work as expected.

Row sub-commands are activated by `r':

.ie c \[shc] \
.  ds softhyphen \[shc]
.el \
.  ds softhyphen \(hy
.na
.TS
tab (@);
l l.
Key@Meaning
_
d@Delete row
i@insert row above
p@paste row
.TE
.ad


.SH FUNCTIONS

ceil

ctime

floor 

hypot

if

life

plus

sqrt

strlen

sum

