.TH NEOLEO 1
.SH NAME
neoleo \- ncurses spreadsheet
.SH SYNOPSIS
.B neoleo
[\fB\-n\fR \fIBITS\fR]
[\fB\-\-bits\fR \fIBITS\fR]
.IR file ...
.SH DESCRIPTION
.B corrupt
modifies files by toggling a randomly chosen bit.
.SH OPTIONS
.TP
.BR \-n ", " \-\-bits =\fIBITS\fR
Set the number of bits to modify.
Default ios one bit.

OK, so lots for me to fill out here.

TABLES:

.ie c \[shc] \
.  ds softhyphen \[shc]
.el \
.  ds softhyphen \(hy
.na
.TS
tab (@);
l c c c.
Description@Octal@latin1@ascii
_
T{
continuation hyphen
T}@255@\*[softhyphen]@-
T{
bullet (middle dot)
T}@267@\(bu@o
T{
acute accent
T}@264@\(aa@'
T{
multiplication sign
T}@327@\(mu@x
.TE
.ad

