.TH NEOLEO 1
.SH NAME
neoleo \- ncurses spreadsheet
.SH SYNOPSIS
.B neoleo
[\fIOPTION\fR]
[\fIFILE\fR]
.SH DESCRIPTION
.B neoleo
is a lightweight spreadsheet based on the venerable GNU Oleo project. Keybindings are styled after vim.
.SH OPTIONS
.TP
.BR \-H ", " \-\-headless
Run in headless mode (without ncurses front-end), man headless-keys for info on commands available in headless mode.
.TP
.BR \-h ", " \-\-help
Show command\-line options
.TP
.BR \-T ", " \-\-tests =\fBX\fR
Run test suite X. X can either be a number or a name. Omit X to obtain a list of tests.
.TP
.BR \-V ", " \-\-version
Show version






.SH FUNCTIONS

ceil

ctime

floor 

hypot

if

life

plus

sqrt

strlen

sum

.SH SEE ALSO
\fBneoleo\-file\fP(5), \fBneoleo\-headless\fP(1), \fBneoleo\-keys\fP(1)
